ingress:
  enabled: true
  className: "external"
  annotations:
    cert-manager.io/cluster-issuer: "internal-ca"
  hosts:
    - host: t.zengarden.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: temperature-monitor-tls
      hosts:
        - t.zengarden.space
